Improve reporting
mild-blue/swagger-unittest pull request #2
Opened 2021-01-20 09:33 UTC by tomaspavlin

I had few difficulties with using this library in mild-blue/txmatching#355. Therefore I introduce few changes. Everything was tested properly.

2021-01-20 11:49 UTC, kubantjan requested changes

2021-01-20 11:49 UTC, kubantjan commented on swagger_unittest/swagger_parser/swagger_parser.py
> +        if not isinstance(dict_to_test, dict):
proc se tohle deje tusis? neni to vec co chce fixnout na vyssi urovni a tady dat jen assert ze to je fakt dict?

2021-01-20 12:56 UTC, tomaspavlin commented on swagger_unittest/swagger_parser/swagger_parser.py
> +        if not isinstance(dict_to_test, dict):
Děje se to v případě, že example hodnota obsahuje někde scalar místo očekávaného dict. `validate_definition` se volá na více místech, všechny by bylo třeba ošetřit. Jednodušší mi to proto připadá ošetřit to tady. Můžu dát pryč typ argumentu dict_to_test.

2021-01-20 15:58 UTC, kubantjan commented on swagger_unittest/swagger_parser/swagger_parser.py
> +        if not isinstance(dict_to_test, dict):
A to je chyba? ma byt ten example vzdycky skalar? Protoze ty tady vratis ze definition je nevalidni. Znamena to, ze takove swagger by nemel byt?

2021-02-07 17:08 UTC, tomaspavlin commented on swagger_unittest/swagger_parser/swagger_parser.py
> +        if not isinstance(dict_to_test, dict):
Tohle se kvůli novému commitu řeší jinak

2021-02-07 17:09 UTC, tomaspavlin commented
Koukám, že tenhle PR už je docela starý a ještě není namergovaný. Rovnou jsem do něho tedy přidal další změny, které potřebujeme kvůli https://github.com/mild-blue/txmatching/pull/422.

2021-02-08 21:00 UTC, kubantjan approved these changes

2021-02-08 21:00 UTC, kubantjan commented on tests/swagger_parser/test_swagger_parser.py
> +    # TODO: also check for correct enum value (currently enum is treated as string)
Please make an issue for that :)

2021-02-08 21:01 UTC, kubantjan commented
We can have a call and setup pipelines for pypi

2021-02-08 21:01 UTC, kubantjan commented
> Koukám, že tenhle PR už je docela starý a ještě není namergovaný. Rovnou jsem do něho tedy přidal další změny, které potřebujeme kvůli [mild-blue/txmatching#422](https://github.com/mild-blue/txmatching/pull/422).

@tomaspavlin  use english here asi it is public repo :)

2021-02-08 21:02 UTC, kubantjan commented on swagger_unittest/swagger_parser/swagger_parser.py
> +        if not isinstance(dict_to_test, dict):
(I forgot to use english here as well :D

2021-02-08 22:04 UTC, kubantjan commented
So i have the pipelines ready, so as soon as we merge this, we can make release and this will create a new version on PiPY and everything should work smoothly after that.

2021-02-09 12:23 UTC, merged